version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - velov-api
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./environment/config.env
    depends_on:
      - redis
    networks:
      - velov-api

networks:
  velov-api:

volumes:
  redis-data:
